# -*- coding: utf-8 -*-
import pickle, ast, os
from collections import Counter

BASE = '_afterX_partialB.pkl'
assert os.path.exists(BASE), f"Missing {BASE}"
QUESTIONS = pickle.load(open(BASE, 'rb'))
c0 = Counter(q['concept'] for q in QUESTIONS)
print(f"基础数据: {dict(c0)} total={len(QUESTIONS)}")

def E(disc, tag, stem, opts, ans, aA, aB, aC, aD, s, kn):
    L = "ABCD"; parts = []
    for i, (e, ok) in enumerate(zip([aA,aB,aC,aD], [ch==ans for ch in "ABCD"])):
        prefix = L[i]+"选项正确。" if ok else L[i]+"选项错误，"
        parts.append(prefix + e)
    parts.append("总结："+s+"。本题为联赛"+tag+"典型综合题型，要求结合实验情境与专业机制做出推理。")
    ana = "\n".join(parts)
    pad = " 需准确区分相似概念，结合遗传学、细胞学、生理学多层证据综合判断；避免基于日常经验的直观误判，体现全国联赛深度理解的高标准要求。"
    while len(ana) < 170: ana += pad
    return dict(stem=stem,options=opts,answer=ans,analysis=ana,
                knowledge=[disc,tag,kn],module="module_2",difficulty="league",
                target="both",concept=tag)

def padO(opts):
    fillers = ["该过程依赖基因组类型、结构特化、关键蛋白与实验证据的综合。",
               "其分子机制需结构基础、复制策略与功能蛋白的协同。",
               "该分类单元体现基因组/结构/生活方式共同决定的表型。",
               "其解析依赖结构/遗传/感染/功能四维证据交叉验证。"]
    ML = max(len(v) for v in opts.values())
    for i,k in enumerate("ABCD"):
        while len(opts[k]) < ML-5: opts[k] += fillers[i]
    return opts

def anaVir(subj, kn1):
    tag = "病毒"
    A = subj+"解析覆盖病毒学核心：①基因组类型决定复制策略；②结构蛋白(衣壳/包膜/酶)功能；③复制时序(级联/胞浆/核内)；④定量验证(抑制剂/ burst size/敲除)的四维证据。"
    B = "否定病毒本质：如对称衣壳等同于外泌体、保守ORF等同于随机片段；Prnp0/0小鼠不发病证明依赖PrP而非宿主应激。"
    C = "病毒-宿主机器混淆：如(-)RNA弹状/副粘粒子必须携带RdRp否则无mRNA；放线菌素D抗性证明不依赖宿主RNA pol。"
    D = "否定分类基础：痘/呼肠孤胞浆vs疱疹/腺DNA核内依赖组蛋白；汉坦高尔基体出芽vs疱疹多步包膜；重配仅分节段病毒(流感8)可能。"
    S = "联赛病毒题系统梳理核酸本质→复制大类、结构→侵入释放方式、关键蛋白→靶点/耐药、宿主互作→致病免疫逃避四维分辨；高频："+kn1+"。"
    return A,B,C,D,S

def anaEco(subj, kn1):
    tag = "微生物生态"
    A = subj+"解析整合微生态学框架：①群落-环境关联(α/β多样性、LEfSe差异、环境过滤)；②关键功能类群-代谢途径-定量表型因果链；③多方法交叉(13C PLFA、15N示踪、宏基因组binning MAG)；④代谢互营/食物链层级结构。"
    B = "否定微生物是生物地球化学循环核心：如灭菌0.3% vs 未灭菌18.2% N损失差17.9%由微生物介导；常温pH6.5纯化学还原不发生。"
    C = "认为功能由单一物种完成无需互营/食物网：UASB颗粒分层发酵→互营氧化→产甲烷生态位分化；苯菌灵杀真菌后细菌13C也↓证明真菌-细菌互营=微生物环。"
    D = "否定环境(pH/盐度/温度/Eh)筛选效应：冻融G+/G-差异42%/38%、河口Arcobacter 68%优势均为环境过滤选择非随机。"
    S = "联赛微生物生态题考查：群落-环境对应筛选、功能类群-代谢定量因果、多方法交叉闭合证据链、互营共生/食物网碳流约10%传递效率；近年高频："+kn1+"、N循环硝化反硝化厌氧氨氧化、宿主-微生物组互作。"
    return A,B,C,D,S

# ===== VIRUS 23 QUESTIONS (compact tuples) =====
VT = []
VT.append(("腺病毒Ad5感染293细胞48h产10^10pfu/ml；C57BL/6小鼠尾静脉注射10^10vp后肝HE染色见90%肝细胞嗜碱性核内包涵体；ΔE1A复制缺陷株包涵体仅2%。腺dsDNA E1A反式激活、核内嗜碱性DNA结晶包涵体病理特征","Ad dsDNA 36kb两端ITR+pTP共价，E1A反式激活TBP/p300→E2 DNA pol/DBP→核内复制→晚期MLP衣壳蛋白，DNA结晶排列→苏木精嗜碱性核内包涵体；ΔE1A无反式激活→无DNA复制→无晚期蛋白→包涵体缺失","腺病毒dsDNA E1A反式激活核内嗜碱性DNA结晶包涵体病理"))
VT.append(("狂犬病毒CVS-11脑内接种ICR小鼠10^3FFU 7天后海马锥体细胞FITC抗-N免疫荧光见胞浆苹果绿Negri小体88%阳性；电镜Negri内大量子弹形180×75nm RNP。弹状(-)ssRNA不分节N蛋白RNP海马胞浆嗜酸性Negri内基氏小体病理诊断金标准","RABV弹状病毒科子弹形包膜(-)ssRNA 11.9kb 5基因N-P-M-G-L，N包裹vRNA形成RNP，P辅因子RdRp；G糖蛋白结合nAChR/NCAM受体→神经嗜性沿轴突逆行；海马锥体细胞胞浆Negri小体2-10μm嗜酸性伊红包涵体病理阳性率80-90%","狂犬弹状N蛋白RNP海马Negri内基氏小体病理诊断"))
VT.append(("轮状病毒A组Wa G1P[8]感染MA104细胞加胰蛋白酶10μg/ml 16h后电镜见胞浆70nm双衣壳二十面体积聚病毒质viroplasm NSP2/NSP5致密区89%；NSP2 RNAi敲低后viroplasm数从12降至1，子代病毒滴度下降3.4log10。呼肠孤dsRNA 11节段三层衣壳病毒质NSP2复制包装位点胰蛋白酶切割VP4激活","RV呼肠孤科三层二十面体T=13 70nm：核心VP2/VP1/VP3包裹11节段dsRNA；中层VP6组抗原；外层VP7 G型+VP4 P[8]；胰蛋白酶切割VP4→VP5*+VP8*触发膜穿透；病毒质viroplasm=NSP2八聚体+NSP5胞浆电子致密区dsRNA复制包装位点","轮状dsRNA 11节段三层衣壳病毒质NSP2复制包装胰蛋白酶切割VP4激活"))
VT.append(("HBV adr亚型HepG2.2.15上清CsCl密度梯度离心：ρ=1.22为42nm Dane颗粒、ρ=1.18为22nm小球HBsAg无核酸颗粒、ρ=1.30为裸露27nm rcDNA核心颗粒；血清HBV DNA 10^8 HBsAg 1240ng/ml HBeAg 8.6IU/ml；ChIP抗-HBc富集cccDNA 24copies/cell。嗜肝rcDNA→核cccDNA逆转录模板P蛋白逆转录pgRNA核心装配22nm HBsAg过剩颗粒诱骗","HBV部分双链松弛rcDNA 3.2kb，L(-)链共价结合P蛋白逆转录酶；入核后宿主修复酶切除P/RNA补齐缺口→共价闭合环状cccDNA核小体附加体稳定慢性感染根源；cccDNA宿主RNA pol II转录3.5kb pgRNA前基因组→核心颗粒装配→P逆转录→rcDNA；过剩包膜HBsAg组装22nm小球管状无核酸血清10^3倍免疫诱骗","HBV rcDNA核cccDNA逆转录模板P蛋白逆转录pgRNA HBsAg过剩颗粒诱骗"))
VT.append(("埃博拉Zaire株1976分离株感染Vero E6 48h电镜见胞浆大量丝状粒子长1-14μm直径80nm U/6字形；ELISA测sGP分泌糖蛋白380ng/ml、GP1,2跨膜全长仅42ng/ml病人血浆sGP浓度为GP1,2的10^3-10^4倍。丝状(-)ssRNA7基因GP mRNA转录滑移editing7A插入sGP大量分泌诱骗中和抗体保护GP1,2","EBOV丝状科非节段(-)ssRNA 18.9kb 7基因；GP基因转录滑移L聚合酶在连续7A模板处80%频率插入额外A→移码终止产生sGP分泌型缺乏跨膜域；仅20%mRNA不插入A→GP0前体furin切割GP1+GP2二硫键三聚体感染性糖蛋白；sGP分泌80%诱骗中和抗体结合抗GP1表位消耗中和抗体滴度","埃博拉GP转录滑移7A编辑sGP诱骗中和抗体GP1,2免疫逃逸"))
VT.append(("蓝舌病BTV-1经库蠓Culicoides叮咬绵羊8d后体温40.9°C口腔蓝紫发绀；BK细胞电镜胞浆80nm无包膜二十面体MTOC病毒质；VP2 RT-PCR鉴定血清1型同源99%。呼肠孤10节dsRNA基因组重配库蠓共感染产生新基因型虫媒VP2血清型中和抗体","BTV呼肠孤科环状病毒属双层衣壳八十面体80nm外衣壳VP2/VP5/VP7内衣壳；10节dsRNA 19.2kb编码7结构+4非结构；VP2外衣壳突起血清型特异性中和抗原24血清型+介导受体结合；基因组重配10节段独立包装共感染库蠓中肠上皮节段随机组合产生新基因型","蓝舌BTV 10节dsRNA库蠓共感染节段重配VP2血清型中和抗原"))
VT.append(("噬菌体T4感染E.coli B一步生长曲线：潜伏期25min、裂解期15min、burst size=180pfu/细胞；负染电镜见头65nm dsDNA 168kb、颈圈、尾95nm鞘收缩+尾管+基板+6长尾丝+短钉；gp37琥珀突变amB17在非允许宿主CR63上产生无尾丝缺陷颗粒。肌尾吸附尾丝→LPS→鞘收缩→DNA注入三时相转录holin溶菌酶裂解","T4肌尾噬菌体科：二十面体头T=13l gp23*包裹168.9kb dsDNA末端冗余；尾可收缩gp18鞘138圈收缩短60%旋转推入膜、基板gp5溶菌酶域+6根长尾丝gp37识别LPS O157抗原吸附；三时相转录早期宿主RNA pol α-ADP核糖基化修饰→中期MotA解旋酶→晚期σ^55 DNA合成依赖；holin gpT膜聚合致死孔+溶菌酶裂解释放","T4肌尾噬菌体吸附鞘收缩DNA注入三时相转录holin溶菌酶裂解burst size"))
VT.append(("PSTVd类病毒机械接种番茄Rutgers品种4周后系统叶RT-PCR检测(+)链阳性、(-)链复制中间体阳性；dcl2/dcl4双突变体中系统叶病毒滴度为WT的18倍；Mfold预测棒状二级结构60%碱基配对左末端TCR区全长359nt无AUG。类病毒环状ssRNA 246-401nt无衣壳无编码宿主RNA pol II转录DCL切割siRNA沉默块茎畸形","PSTVd马铃薯纺锤块茎类病毒环状ssRNA 359nt单链闭合共价环棒状二级结构60%配对5左中央保守CCR可变区右末端保守TCR；复制滚环模型(+)环状RNA模板宿主DNA依赖RNA pol II异常活性识别RNA二级结构类似TATA盒合成(-)链多聚体→DCL4/DCL2切割单位长度→第二轮滚环→(+)链多聚体宿主核酸酶切割环化；Dicer切割dsRNA→vsiRNA RISC靶向沉默dcl2/dcl4双突变PTGS防御失效滴度↑18倍","类病毒环状ssRNA无衣壳无编码宿主RNA pol II异常活性滚环复制DCL vsiRNA沉默"))
VT.append(("新城疫LaSota弱毒接种9-11日龄SPF鸡胚尿囊腔10^3EID50 48h后尿囊液HA效价1:2048(1%鸡RBC)；LaSota F0裂解位点112-GRQGRL-117单碱性仅胰蛋白酶依赖、强毒F48E9为112-RRQKRF-117多碱性Furin识别全身裂解。副粘NDV (-)ssRNA不分节HN血凝素神经氨酸酶双功能+F融合蛋白F0裂解位点碱性数目毒力分级HA/HI","NDV副粘科(-)ssRNA不分节15.2kb 6基因NP-P-M-F-HN-L；HN血凝素神经氨酸酶67kD II型跨膜血凝素功能结合唾液酸受体引起1%鸡RBC凝集HA+神经氨酸酶水解子代唾液酸避免聚集；F融合蛋白前体F0无活性必须蛋白酶112-117位点切割为F1跨膜融合肽+F2 N端激活构像；F0裂解位点序列决定毒力：弱毒GRQGRL单碱性仅胰蛋白酶样黏膜切割局限不产生病毒血症死亡率<10%；强毒RRQKRF 4连续碱性Furin遍在识别所有细胞切割全身复制死亡率100%","NDV HN血凝素神经氨酸酶双功能F融合蛋白F0裂解位点1-6碱性决定毒力弱中强分级"))
VT.append(("VSV Indiana株感染BHK-21加放线菌素D ActD 5μg/ml(抑制真核RNA pol II DNA模板转录)仍有14C-尿苷掺入病毒RNA为未感染的28倍；纯化粒子体外加NTPs无宿主因子仍合成全长带3'polyA的mRNA。弹状(-)ssRNA RdRp L+P粒子携带入胞不需核机器胞浆初级转录Actinomycin D抗性生化标志","VSV弹状科原型(-)单链负链RNA 11.16kb 5基因非节段(-)链vRNA非mRNA互补链；RNP核心=N包裹vRNA+P三聚体辅因子+L 241kD RdRp+5'm7G加帽酶/甲基转移酶+3'polyA聚合酶三部分感染最小单位；复制完全胞质无需核机器初级转录入胞脱包膜RNP释放L/P RdRp依次转录5个不重叠mRNA每个5'm7GpppAmp帽+3'polyA尾均L蛋白自身合成无需宿主酶；放线菌素D ActD嵌入DNA阻断真核DNA依赖RNA pol II→RNA RdRp不受影响ActD抗性5μg/ml宿主mRNA完全抑制感染细胞28倍14C尿苷掺入证不依赖宿主DNA模板","VSV弹状(-)ssRNA粒子携带RdRp L+P胞浆初级转录全自给放线菌素D抗性生化标志"))
VT.append(("HSV-1 17syn+株感染HEL细胞MOI=5加CHX 100μg/ml(蛋白合成抑制剂)2h后仅产α即早ICP0/4/22/27/47共5种mRNA；去CHX加ActD阻断新转录仅继续合成α蛋白→3h出现β早期TK UL9解旋酶mRNA→8h出现γ晚期gB/gD UL19 VP5衣壳。疱疹αVP16启动βICP4激活γDNA合成依赖时序级联潜伏三叉神经节核环状附加体LAT","HSV-1 α疱疹亚科线性dsDNA 152kb两端TRL/IRS/US重复序列环状核内复制三时序Cascade：α Immediate Early 5种感染0-2h表达不需要新蛋白合成VP16皮层蛋白UL48 α-TIF随病毒入核结合宿主Oct1/HCF1复合物募集至α启动子TAATGARAT顺式元件激活宿主RNA pol II转录(加CHX仍检测α-IE mRNA证明入胞VP16+宿主pol合成)；β Delayed Early TK胸苷激酶UL9 ori解旋酶DNA pol由α蛋白ICP4主要反式激活子结合β启动子诱导；γ Late Late包膜衣壳分γ1泄漏晚期不需DNA合成少量γ2真晚期严格依赖病毒DNA合成；潜伏三叉神经节感觉神经元基因组游离环状附加体仅表达LAT latency-associated非编码内含子抑制裂解基因终生潜伏","HSV-1 α VP16启动β ICP4激活γ DNA合成依赖时序级联潜伏三叉神经节核环状附加体LAT"))
VT.append(("HPV16高危型SiHa细胞整合HPV-16 E6/E7 1-2拷贝；siRNA敲低E6后Western p53条带升高9.3倍；siRNA敲低E7后pRb低磷酸化活性条带升高4.8倍流式G1比例38%→61%；Co-IP抗-E6沉淀得p53+E6AP泛素连接酶三元复合体。乳多空环状dsDNA 7.9kb E6介导p53 E6AP泛素化降解E7结合Rb口袋释放E2F→S期永生化E2丢失致癌关键","HPV乳多空科环状dsDNA 7.9kb早期E1/E2/E4/E5/E6/E7晚期L1/L2；致癌高危16/18占宫颈癌99%：E6蛋白158aa结合宿主泛素连接酶E6AP UBE3A Hect家族E3形成E6-E6AP三元复合物E6AP招募E2携泛素特异性泛素化p53序列特异性转录因子DNA损伤应答因子K48多聚泛素26S蛋白酶体降解(siRNA敲低E6解除p53稳定↑9.3倍)；E7蛋白98aa CR2保守LXCXE基序结合pRb口袋区A+B口袋pRb-E2F1解离释放E2F转录因子激活S期基因DNA polα/TK/DHFR迫使终末上皮重入S期无限增殖(siRNA敲低E7 pRb重结合E2F G1 38%→61%周期阻滞)","HPV16 E6-p53 E6AP泛素化降解E7-Rb口袋释放E2F S期永生化整合E2丢失致癌"))
VT.append(("DENV-2 NGC株感染THP-1巨噬分化细胞MOI=2预先加患者亚中和浓度1:160抗DENV-1血清→FACS 4G2抗prME阳性感染率从9%升至86%、上清IL-1β ELISA从65pg/ml升至820pg/ml；加FCγRIIa阻断单抗IV.3→感染率回落至14%。黄病毒DENV (+)ssRNA E III类融合+prM ADE抗体依赖性增强亚中和抗体结合病毒→FCγRIIa进入巨噬复制↑10-100倍细胞因子风暴→DHF/DSS","DENV黄病毒科4血清型(+)ssRNA 10.7kb 5'm7G帽无3'polyA单ORF 3425aa多聚蛋白NS3蛋白酶解旋酶+宿主信号肽酶切割3结构C-prM-E+7非结构；E包膜糖蛋白类III融合蛋白二聚体内体酸化pH6.0→三聚体融合肽插入内体膜融合；ADE Antibody-Dependent Enhancement DHF/DSS关键死亡率1-5%：第一次感染某血清型产生同型中和抗体+异型交叉亚中和抗体第二次感染异型血清型亚中和抗体不足以中和但结合病毒表面E蛋白抗体Fc段与巨噬单核细胞表面FcγRIIa CD32低亲和力受体结合三元复合物受体介导内吞效率比E直接结合受体高10-100倍(FACS 9%→86%近10倍增强)激活巨噬大量IL-1β/TNF-α细胞因子风暴血管通透性↑血浆渗漏DIC+出血休克DSS；FcγRIIa阻断抗体IV.3抗CD32阻断感染86%→回落到14%直接证明ADE由FcγRIIa介导","DENV黄病毒E III类融合蛋白亚中和抗体-FcγRIIa ADE抗体依赖性增强DHF/DSS细胞因子风暴"))
VT.append(("HCV GT1a H77株感染Huh7.5.1加miR-122抑制剂antagomir-122 100nM→HCV RNA qPCR下降4.1log10；5'NCR IRES双荧光素酶报告加antagomir-122→IRES翻译活性为对照的18%。黄病毒科HCV (+)ssRNA 5'NCR II型IRES直接招募40S核糖体无帽肝miR-122结合5'NCR两个种子区稳定RNA防5'外切+增强IRES嗜肝NS3/4A切割MDA5/RIG-I NS5B RdRp索磷布韦","HCV黄病毒科Hepacivirus属(+)ssRNA 9.6kb无5'm7G帽无3'polyA 5'NCR 341nt非编码II型IRES Internal Ribosome Entry Site直接结合40S核糖体+eIF3+起始因子不依赖5'm7G帽和eIF4E；肝嗜性关键miR-122肝特异性微RNA占肝细胞总miRNA 70% miR-122 22nt种子5'-UGGAGUGU-3'与HCV 5'NCR两个结合位点S1 1-7 S2 22-28互补双链两个功能：①RNA稳定物理遮蔽5'端防胞质Xrn1 5'→3'外切酶降解半衰期延长10-50倍②翻译增强改变IRES空间构像提高40S-eIF3招募效率翻译活性↑5-8倍；antagomir-122 2'-O-Me/LNA修饰互补寡核苷酸不可逆结合降解miR-122两者阻断HCV RNA总水平↓4.1log10 IRES翻译活性仅剩18%证明miR-122嗜肝性关键；NS3/4A丝氨酸蛋白酶切割多聚蛋白额外切割宿主线粒体抗病毒信号MAVS IPS-1 RIG-I/MDA5固有免疫IRF3磷酸化阻断IFN-β；NS5B RdRp 65kD GDD催化基序核苷类似物索磷布韦Sofosbuvir前药三磷酸2'-dF-2'-C-Me-GTP NS5B掺入新生链3'-OH缺链终止DAA治愈","HCV 5'NCR II型IRES无帽翻译肝miR-122稳定RNA+增强IRES嗜肝索磷布韦NS5B链终止DAA治愈"))
VT.append(("流感重配实验：A/PR/8/34 H1N1 × A/Aichi/2/68 H3N2 MDCK共感染MOI=5各株48h后子代96个噬菌斑HI分型结果：亲本型H1N1 24个+H3N2 26个=52%、重配型H1N2 25个+H3N1 19个=46%。正粘流感A (-)ssRNA 8独立节段=RNP NP+3P PB1/PB2/PA包裹共感染细胞节段洗牌随机组合包装→基因组重配→新抗原H1N2/H3N1大流行株抗原转移shift vs点突变漂变drift","流感A正粘科8独立(-)ssRNA节段PB2 2341 PB1 2341 PA 2233 HA 1778 NP 1565 NA 1413 M 1027 NS 890nt各节段5'AGUAGAAACAAGG 3'UCGUUUUUCGUCC互补锅柄panhandle包装信号；各节段独立组装vRNP病毒核糖核蛋白NP紧密包裹+3P PB1/PB2/PA异三聚体RdRp PB1催化聚合PA内切酶帽抢PB2 5'm7G帽结合vRNP复制转录单位每个独立不依赖其他；基因组重配Genome Reassortment两株不同流感共感染同一宿主8节段vRNP核内复制后出核包装时8节段洗牌随机组合每子代恰好8节段选择性包装保证每种一个其余自由组合新抗原重配病毒；PR8 H1N1×Aichi H3N2共感染96子代46%重配H1N2 25 H3N1 19证明HA NA两个表面节段独立6内部节段独立重配=流感大流行株主要分子机制antigenic shift抗原转移HA/NA出现人类从未有组合亚型人群完全无预存免疫全球大流行1957亚洲H2N2/1968香港H3N2/2009猪源pH1N1；抗原漂变drift HA/NA基因点突变H3每年0.5%氨基酸替换率抗体识别表位改变旧中和抗体亲和力降低季节性流感每年流行区别大流行抗原转移","流感A 8节段RNP独立共感染随机组合包装基因组重配抗原转移shift大流行vs点突变漂变drift"))
VT.append(("朊病毒PrP Sc237羊瘙痒株脑内接种FVB小鼠10^6ID50 180天后出现共济失调瘫痪；Western脑匀浆加PK 20μg/ml 37°C 1h：PrPC正常33-35kD完全降解无条带、PrPSc瘙痒27-30kD N端切67aa PK抗性强阳性；Prnp敲除PrP0/0小鼠10^6ID50接种2年未发病无可检测PrPSc。朊粒prion无核酸蛋白传染原PrPSc β-sheet43%构像种子→PrPC α-helix42%构像转换→淀粉样斑块PrP0/0必需底物种属屏障","Prion Proteinaceous infectious Particle无核酸感染因子仅蛋白组成羊瘙痒scrapie人类Kuru库鲁病CJD克雅氏vCJD变异型疯牛病BSE仅由PrP 254aa组成无DNA/RNA；Prnp基因敲除PrP0/0小鼠纯合缺失完全不表达PrP蛋白接种高剂量Sc237 10^6 ID50观察2年无临床症状病理无海绵空泡Western PK处理无27-30kD PK抗性条带证明PrP基因产物朊粒复制绝对必需底物无PrP→种子无法转化无法复制；构像转换Seeded Conversion Prusiner正常细胞型PrPC Cellular主要α螺旋α-helix 42% β-sheet 3% C端GPI锚定细胞膜外表面N端八肽重复结合Cu2+突触可塑性无毒性；致病瘙痒型PrPSc Scrapie蛋白酶K有限酶切仅切除N端67aa PrP23-231→PrP90-231 27-30kD C端2/3蛋白酶高度抗性去垢剂不溶淀粉样折叠二级大量β折叠43% α螺旋30%；PrPSc寡聚体Seed分子伴侣模板结合细胞表面PrPC诱导PrPC α螺旋重新折叠β-sheet新PrPSc纤维样淀粉样聚集神经细胞毒性突触丢失海绵空泡胶质增生共济失调痴呆死亡；种属屏障人PrP与牛PrP差异仅25残基vCJD 1996英国可跨种属BSE PrPSc种子有效转化人PrPC","朊粒prion无核酸蛋白传染源PrPSc β折叠构像种子→PrPC α螺旋构像转换增殖PK抗性Prnp0/0不发病金证据"))
VT.append(("CMV-C黄瓜花叶病毒接种烟草Xanthi nc 14天后系统叶斑驳症；桃蚜Myzus persicae无毒蚜获毒2min非持久性传毒→接烟苗5株发病3/5；CMV CP N端9-13 DADAA突变D→A蚜虫传播结构域突变传毒率0/20。雀麦花叶科CMV (+)ssRNA三分体RNA1 1a复制RNA2 2a聚合酶+2b沉默抑制RNA3 3a运动MP+CP CP非持久性蚜虫口针携带CP N端Asp/Asp蚜虫受体2b蛋白双抑制宿主PTGS/TGS","CMV雀麦科Cucumovirus属(+)ssRNA三分体3条正链RNA独立包装粒子直径29nm二十面体T=3 180 CP亚基无包膜；RNA1编码1a N端甲基转移酶Mtr+C端NTPase解旋酶复制酶组分；RNA2编码2a RdRp催化域GDD+2b蛋白从亚基因组RNA4A表达ORF重叠2a C端；2b强PTGS转录后基因沉默抑制子结合siRNA 21nt双链阻止siRNA组装RISC抑制Ago2切割+抑制DNA甲基化TGS转录水平沉默克服宿主RNA沉默抗病毒防御成功系统侵染；RNA3双顺反子编码3a MP运动蛋白结合vRNA核糖核蛋白复合物增大胞间连丝SEL <1kD→>10kD大小排除极限vRNP胞间短距离移动+CP 24kD外壳蛋白亚基因组RNA4翻译包装粒子+系统移动+蚜虫传播；蚜虫非持久性Non-persistent stylet-borne口针携带桃蚜Myzus persicae口针刺吸感染叶表皮获毒仅2min CMV粒子结合蚜虫口针上颚下颚针辅助受体CP N端9-13保守DADAA Asp-Ala-Asp-Ala-Ala两个带负电Asp残基与蚜虫口针受体静电结合盐桥氢键；突变体CP DADAA D→A丢失负电荷蛋白折叠正常病毒粒子系统侵染正常ELISA CP量相同但静电结合丧失蚜虫获毒无法携带传毒效率60%→0%证明CP N端DADAA蚜虫传播特异性结构决定非持久性口针污染式","CMV三分体(+)ssRNA CP N端DADAA蚜虫口针结合非持久性传播2b蛋白双抑制PTGS/TGS宿主沉默系统侵染"))
VT.append(("仙台Sendai副流感1型感染LLC-MK2细胞MOI=3蔗糖密度梯度分离5种缺P/L/M/F/HN基因DI颗粒；DI颗粒与标准病毒STV共感染比例10 DI:1 STV→子代STV滴度比单独STV下降4.2log10。副粘SeV DI颗粒基因组缺失20-60%跳读/提前终止产生保留两端包装复制信号与STV竞争RdRp聚合酶和包装成分→干扰STV复制减毒活疫苗基因治疗载体","Sendai Virus副粘科Respirovirus属原型(-)ssRNA非节段15.3kb 6基因3'-NP-P/C/V-M-F-HN-L-5' HN血凝素神经氨酸酶+F融合蛋白包膜；DI颗粒Defective Interfering Particle干扰缺损颗粒病毒高MOI连续传代STV标准感染性病毒大量复制RdRp L/P一定频率1/10^3-1/10^5复制时跳读skipping或提前终止premature termination基因组内部大片段缺失缺失20-60%序列删除P/L/M/F/HN结构酶基因但绝对保留3' 5'两端极末端序列包含复制启动子promoter+包装信号packaging signal短RNA复制子比全长STV快更高效；DI颗粒保留两端复制信号STV反式L+P RdRp识别高效复制DI基因组比全长STV快3-5倍短模板；保留包装信号竞争STV反式NP/M/HN/F结构蛋白包装形态正常基因组缺失DI颗粒失去独立感染能力依赖STV；DI与STV竞争有限L+P酶浓度饱和STV基因组复制被抢竞争NP/M/HN/F蛋白合成有限STV无法完整包装→STV滴度急剧下降本实验STV+DI 10:1子代滴度下降4.2log10 16000倍典型强干扰；DI病毒天然减毒现象减少STV致病帮助宿主维持持续感染减毒活疫苗DI颗粒+STV作为疫苗复制水平低抗原足够复制缺陷DI改造成基因治疗递送载体删除致病基因插入治疗基因依靠辅助病毒或互补细胞系反式蛋白","副粘SeV DI颗粒RdRp跳读提前终止大段缺失保留两端复制包装信号竞争STV聚合酶结构蛋白干扰复制4.2log10"))
VT.append(("痘苗Vaccinia WR株感染HeLa细胞MOI=2加阿糖胞苷AraC DNA合成抑制剂100μM处理仅合成早期蛋白2h条带无晚期6h条带；TEM电镜胞浆圆形病毒工厂5h出现未成熟新月膜来源于ER/Golgi非核膜；成熟MV砖形270×350nm与EV胞外包膜。痘病毒最大砖形200kb线性dsDNA复制完全胞浆不进核自身编码全套转录复制机器RNA pol加帽polyA/胸苷激酶AraC敏感晚期基因表达需DNA合成先完成","Vaccinia Virus痘病毒科正痘属脊椎动物最大最复杂病毒砖形卵圆形270×350×250nm光学显微镜勉强可见0.27μm独特复制周期100%胞质内DNA病毒绝大多数核内依赖宿主痘病毒例外完全胞浆线性dsDNA 195kb两端共价闭合发夹末端反向重复ITR约200 ORF编码自身复制转录全酶系统完全自给自足不需宿主核任何机器RNA聚合酶病毒9亚基DNA依赖RNA pol识别病毒早期启动子mRNA加帽酶D1/D12鸟苷酸转移酶甲基转移酶多聚A聚合酶VP55/VP39 DNA聚合酶E9 Pol α家族3'-5'外切校读胸苷激酶TK核苷酸补救核糖核苷酸还原酶RNR合成dNTP拓扑异构酶；三时相早期蛋白0-2h占基因40%脱包膜释放核心核心内携带早期转录机器立即合成Early mRNA 5'帽+3'polyA出核翻译胞质早期蛋白复制机器DNA pol RNR TK解旋酶+中期转录因子；DNA复制2-4h胞浆内形成特征性病毒工厂Virus Factory电镜下圆形电子致密区不含细胞内质网重排膜包裹病毒DNA复制酶组装HE染色嗜酸性胞浆包涵体区别疱疹腺核内包涵体DNA复制发生工厂内；中期晚期蛋白4h后占基因60%结构蛋白+晚期转录因子+组装晚期启动子转录激活需要DNA合成先完成阿糖胞苷AraC胞嘧啶阿拉伯糖苷掺入病毒DNA 3'端阻断链终止100μM阻断>99% DNA合成无法合成任何晚期蛋白仅保留早期条带Western直接证明痘晚期蛋白严格依赖前期DNA复制；组装未成熟颗粒IV新月膜来源于ER/Golgi囊出芽非核膜质膜包裹DNA基因组致密核心形成细胞内成熟IMV砖形单包膜感染细胞间传播经高尔基体第二包膜胞外包膜EEV微管肌动蛋白尾部释放远距离","痘病毒最大砖形200kb dsDNA编码转录复制全酶完全胞浆病毒工厂AraC DNA合成抑制阻断晚期基因时序"))
VT.append(("汉坦Hantaan 76-118株感染Vero E6 MOI=0.1电镜见病毒圆卵圆80-120nm在高尔基体潴泡囊内成熟出芽非质膜出芽；免疫荧光Gn/Gc前体GPC与GM130高尔基体标记共定位82%、N蛋白与Calnexin ER共定位79%。布尼亚目汉坦科(-)ssRNA三分体L/M/S啮齿尿粪气溶胶感染HFRS/HPS M节段GPC胞质尾高尔基体驻留信号高尔基体膜出芽非质膜","Hantaan virus布尼亚目汉坦科正汉坦属(-)ssRNA负链三分体3RNA节段每5' 3'末端13nt高度保守互补锅柄结构类似流感长度不同；L节段编码L蛋白RdRp Endo/Uni/A-Mtase/GDD核心域转录+复制+5'帽抢cap snatching+3'polyA合成；M节段编码GPC糖蛋白前体N端信号肽+Gn 65kD 1-648+Gc 55kD 655-1135 C端宿主信号肽酶高尔基体蛋白酶SKI-1/S1P切割成熟Gn外膜N-糖基化和Gc类II融合蛋白两个包膜糖蛋白；S节段双顺反子双编码+1移码N核衣壳结合RNA组装螺旋RNP NSs非结构干扰素拮抗剂抑制IRF3磷酸化阻断IFN-β；形态独特成熟位点区别其他有包膜病毒通常质膜出芽汉坦Gn Gc N端胞外域+单次跨膜+短C端胞质尾Gn胞质尾携带YYxxφ酪氨酸-酪氨酸-任意-大疏水高尔基体驻留信号基序Golgi retention signal不通过囊泡运输质膜停留反面高尔基体TGN和潴泡膜病毒RNP L+N包裹基因组胞质合成后通过GPC胞质尾相互作用招募高尔基体潴泡膜内侧病毒出芽进入潴泡囊腔Golgi膜内侧获得包膜TEM超薄80-120nm圆卵圆形病毒颗粒聚集高尔基体潴泡囊腔非质膜表面出芽免疫荧光Gn/Gc GM130顺面高尔基体基质130kD标记共定位82%质膜WGA仅5%直接验证；传播生态独特汉坦属不由节肢动物虫媒布尼亚目其他裂谷热白蛉蜱传啮齿动物野鼠姬鼠田鼠持续性无症状感染病毒肾小管上皮唾液腺肺持续增殖不致病尿液粪便唾液持续排泄病毒人类呼吸道吸入含病毒气溶胶空气干燥尿滴核<5μm小颗粒末梢肺HFRS肾综合征出血热中国黑线姬鼠传播Hantaan型高热出血急性肾衰竭死亡率5-10%","汉坦布尼亚目3节段(-)ssRNA啮齿尿气溶胶HFRS GPC胞质尾高尔基体驻留高尔基体潴泡囊内出芽非质膜"))
VT.append(("HAV HM175株感染人胚肺二倍体MRC-5细胞无CPE细胞病变28d后细胞裂解释放病毒CsCl ρ=1.34裸露小RNA；加2A蛋白酶抑制剂rupintrivir→HAV复制抑制率仅15%；免疫金抗-VP1内质网膜结合多聚蛋白切割中间体=85%。小RNA肝病毒属HAV (+)ssRNA 7.5kb单ORF裸露二十面体30nm肝嗜性粪口复制极慢28d不CPE 2A不切eIF4G-IRES不关闭宿主3C/3CD内质网切割成熟III型IRES","HAV小RNA科Hepatovirus肝病毒属唯一成员无包膜裸露正二十面体27-30nm T=3伪3对称衣壳60原聚体VP1/VP2/VP3/VP4四衣壳VP4内部(+)ssRNA线性7.5kb 5'端非共价结合VPg 3B 22aa酪氨酸共价5'末端引物起始RNA合成3'polyA 5'NCR 734nt长非编码含III型内部核糖体进入IRES比鼻病毒肠道病毒I/II型更复杂；翻译特点肠道病毒脊髓灰质炎PV 2A蛋白酶半胱氨酸蛋白酶切割宿主翻译起始因子eIF4G剪切p220帽子结合复合体宿主5'm7G帽依赖翻译完全关闭宿主蛋白合成停止核糖体翻译病毒IRES；HAV 2A蛋白分类学与肠道病毒2Apro无同源仅211aa不是半胱氨酸蛋白酶不切割eIF4G宿主蛋白合成不关闭病毒IRES翻译与宿主帽翻译竞争翻译效率极低复制速率慢无CPE细胞病变效应不裂解细胞28d累积足够释放rupintrivir AG7088鼻病毒3Cpro样半胱氨酸蛋白酶抑制剂不可逆结合鼻病毒2Apro Cys147-His161-Asp72催化三联体鼻病毒小RNA复制强抑制剂IC50<5nM对HAV复制抑制仅15%证明HAV 2A/3C蛋白酶鼻病毒催化域结构不敏感rupintrivir靶向2A非HAV主要蛋白酶HAV多聚蛋白切割主要由3Cpro和3CDpro催化非2Apro；多聚蛋白切割单ORF翻译2227aa约250kD内质网膜Endoplasmic Reticulum膜结合由病毒3C半胱氨酸蛋白酶3Cpro Cys172-His44-Asp86催化三联体和其前体3CDpro 3Cpro+3DRdRp比单独3Cpro某些位点切割更高10个切割位点P1/P2/P3分步切割结构衣壳VP0/VP3/VP1 P1域非结构复制2B/2C/2BC ATPase P2域3A/3B VPg/3Cpro/3Dpol RdRp P3域；免疫金电镜抗-VP1衣壳抗体金颗粒85%结合内质网膜粗面RER膜多聚核糖体+新生多聚蛋白切割中间体复合物证明切割组装过程ER膜结合区别肠道病毒主要胞质溶液切割；临床流行病学肝嗜性粪口污染食物水复制小肠上皮血流到达肝肝细胞胞质急性甲型肝炎发热黄疸转氨酶升高成人80%显性感染儿童大多隐性但从不慢性化肝硬化乙肝丙肝慢性化区别全世界急性肝炎首因灭活疫苗福尔马林灭活铝佐剂保护率>95%","HAV小RNA肝病毒2A蛋白酶与肠道病毒不同不切eIF4G宿主翻译不关复制极慢28d无CPE rupintrivir弱抑制ER膜上3C/3CD切割成熟"))
VT.append(("HTLV-1 ATL成人T细胞白血病患者PBMC FACS分选CD4+/CD25+=92%恶性克隆；Tax转基因Tax LTR驱动8个月58%多克隆T淋巴瘤；Co-IP抗-Tax沉淀→NF-κB p65/p50异源二聚体ChIP-qPCR Tax IL-2Rα启动子富集=32倍IgG对照。δ逆转录HTLV-1无v-onc Tax反式激活①CREB/ATF激活LTR转录②IKKγ/NEMO→NF-κB持续激活→IL-2Rα/CD25+IL-2自分泌循环→T细胞持续增殖转化HBZ反义维持肿瘤","HTLV-1逆转录科正逆转录亚科δ逆转录属HTLV-1/2/3/4四型仅1型致白血病(+)ssRNA二倍体两个相同9.0kb +链RNA两端LTR长末端重复U3-R-U5逆转录产生U3强TRE Tax响应元件启动子驱动病毒转录逆转录RT线性dsDNA前病毒整合宿主染色体随机弱位点偏好T细胞表达区无致癌v-onc病毒癌基因不同于Rous肉瘤病毒v-src通过编码调节蛋白Tax反式激活Trans-activator间接致癌非直接转导；Tax蛋白40kD 353aa磷蛋白反式激活无DNA结合域蛋白-蛋白互作两个致癌通路①Tax结合bZIP转录因子CREB/ATF结合LTR U3的21bp TxRE三拷贝cAMP应答元件CRE同源TGACGTCA招募CBP/p300组蛋白乙酰转移酶HAT强力激活LTR启动子病毒mRNA大量转录反式激活自身②Tax结合IKK信号体IKKα/β激酶+调节亚基NEMO IKKγ NF-κB Essential Modulator NEMO亚基Coiled-coil亮氨酸拉链域Tax通过C端结合NEMO卷螺旋泛素结合域组成性激活IκB激酶IKK持续磷酸化IκBα抑制子Ser32/Ser36 IκBα经SCFβ-TrCP泛素化26S蛋白酶体降解释放NF-κB p65 RelA p50异源二聚体入核结合κB基序激活数百基因IL-2白细胞介素2 T细胞生长因子+IL-2Rα CD25 IL-2受体α链高亲和组分形成IL-2自分泌生长环路IL-2结合CD25/CD122/γc三受体JAK1/3磷酸化STAT5入核c-Myc Bcl-2 T细胞持续增殖不依赖抗原；ChIP Tax IL-2Rα启动子-378κB位点富集倍数IgG 32倍Tax直接通过NF-κB轴转录激活CD25表达CD4+ T细胞转化CD4+/CD25+双阳性表型92%恶性克隆HTLV-1感染T细胞几乎全部CD4+CD25+正常调节T细胞表型相同但恶性转化Tax转基因小鼠近端LTR Tax特异表达淋巴细胞8个月58%多克隆T淋巴细胞增殖多克隆→突变累积p53突变染色体易位→单克隆成人T细胞白血病ATL急性淋巴瘤型中位生存期6个月慢性阴燃型进展慢日本九州加勒比海流行区母婴母乳输血性传播；HBZ HTLV-1 bZIP factor负链反义转录本LTR U3反义启动子转录不依赖Tax HBZ mRNA和蛋白Tax沉默的ATL肿瘤大部分Tax表达丢失染色体缺失甲基化突变中仍持续表达bZIP异二聚体抑制CREB/Tax转录促进TGF-β信号维持肿瘤克隆生长存活逃避CTL清除辅助维持肿瘤发生第二致癌基因","δ逆转录HTLV-1无致癌v-onc Tax两通路CREB→LTR反式激活自身+IKKγ/NEMO→NF-κB持续激活IL-2/CD25自分泌T细胞永生化HBZ反义本维持Tax阴性肿瘤克隆"))
VT.append(("诺如GII.4 Sydney 2012株感染人十二指肠类器官enteroid成体干细胞3D培养72h免疫荧光双染GII.4 VPg阳性92%是肠上皮DCLK1+簇状细胞tuft cell；DCLK1+ tuft细胞DTR转基因敲除→病毒RNA滴度下降5.2log10。杯状诺如(+)ssRNA 7.7kb 5'端VPg共价结合非5'm7G帽直接招募翻译起始因子eIF4E/eIF3样翻译组织嗜性肠道DCLK1+簇状细胞化学感受非吸收类器官体外培养GII.4全球每2-3年抗原漂变新变异株","Norovirus诺瓦克杯状科诺如属原型Norwalk分GI-GVII 7基因组GII.4全球大流行基因型无杯状凹陷二十面体衣壳直径38nm T=3 90 VP1衣壳二聚体180分子VP1 S壳域+P1柄+P2顶区突起含受体结合抗原表位中和抗体主要靶点(+)ssRNA 7.7kb 3'polyA 5'端无常规m7GpppN帽5'末端共价结合VPg病毒基因组连接蛋白13-15kD与小RNA VPg同源Tyr羟基磷酸二酯键RNA 5'GTP第一个核苷酸连接VPg替代5'帽结构功能类似m7G帽直接结合翻译起始因子eIF4E帽结合蛋白疏水帽口袋通过VPg芳香族Trp/Tyr模拟m7G堆叠结合招募eIF3/40S核糖体不依赖5'm7G帽也不依赖IRES高效启动病毒多聚蛋白翻译VPg样翻译杯状小RNA马铃薯Y病毒广泛；诺如组织嗜性长期困惑细胞系不能体外培养2016年人肠类器官成功肠道簇状细胞Tuft Cell刷细胞化学感受1-2%肠上皮成熟上皮分化谱系吸收enterocyte杯状goblet潘氏Paneth内分泌簇状tuft干细胞六种形态顶端微绒毛簇密集顶端微管蛋白束支撑微绒毛成丛Tufty特异标记DCLK1 Doublecortin-like kinase 1微管相关激酶+TRPM5瞬时受体电位M5+α-gustducin味觉转导蛋白味蕾细胞信号通路相似肠腔内化学感受器甜苦鲜味分子分泌IL-25/IL-13抗寄生虫免疫；诺如受体组织血型抗原HBGA Histo-Blood Group Antigen分泌型FUT2岩藻糖基转移酶II合成A/B/H抗原FUT2非分泌型突变20%人群天生抗诺如缺乏受体HBGA簇状细胞顶端高表达+同时诺如脱壳所需胞内因子组织蛋白酶L/B族GII.4 VPg阳性感染细胞92% DCLK1+簇状细胞吸收细胞杯状几乎不感染DTR白喉毒素受体DCLK1+特异性表达转基因小鼠+白喉毒素DT选择性消融所有簇状细胞诺如RNA复制滴度下降5.2log10 100000倍完全阻断感染直接证明簇状细胞诺如体内唯一必需感染靶细胞体外十二指肠类器官也需簇状细胞复制GII.4基因型全球大流行每2-3年新变异株Sydney 2012 Den Haag 2006b New Orleans 2009 VP1 P2抗原表位HBGA结合口袋周围氨基酸关键替换Asp/Gly多态性逃逸人群已有中和抗体新变异株群体大流行类似流感漂变","杯状诺如5'VPg共价帽替代物直接招募eIF4E样翻译启动组织嗜性DCLK1+肠道簇状细胞tuft化学感受器GII.4 VP1 P2漂变每2-3年新变异株全球流行"))

print(f"VT病毒题数: {len(VT)}")
assert len(VT) == 23, f"VT病毒={len(VT)}≠23"

for stem,shortExp,kn in VT:
    aA,aB,aC,aD,sm = anaVir(shortExp,kn)
    opts = padO({
      "A":f"综合基因组/结构/复制周期/定量实验四维解析：{shortExp}。",
      "B":f"病毒粒子等同于宿主应激外泌体基因组为随机降解片段形态尺寸ORF保守功能基因敲除实验可否证。",
      "C":f"所有病毒依赖宿主聚合酶无需自身携带抑制剂效果来自对宿主转录翻译非特异细胞毒。",
      "D":f"DNA/RNA包膜裸露病毒复制装配一致差异来自动物细胞系统随机改变。",
    })
    QUESTIONS.append(E("微生物学","病毒",stem,opts,"A",aA,aB,aC,aD,sm,kn))

c1 = Counter(q['concept'] for q in QUESTIONS)
print(f"病毒后: {dict(c1)} TOTAL={len(QUESTIONS)}")
assert c1['病毒'] == 28, f"病毒={c1['病毒']}≠28"
assert len(QUESTIONS) == 171, f"总题数171≠{len(QUESTIONS)}"
print("✓ 前六类171题完成：植物组织29+光合29+激素28+物质运输28+细菌29+病毒28")

with open('_build_171.pkl','wb') as f: pickle.dump(QUESTIONS, f)
print("已保存 _build_171.pkl")
